# Generated by Django 5.2.5 on 2025-08-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_form',
            new_name='Contact_message',
        ),
        migrations.AlterModelOptions(
            name='contact_message',
            options={'verbose_name': 'Contact_message', 'verbose_name_plural': 'Contact_messages'},
        ),
    ]
