# Generated by Django 5.2.5 on 2025-08-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_rename_contact_form_contact_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_image', models.ImageField(upload_to='web_image')),
                ('website_name', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('website_url', models.URLField()),
                ('tools', models.ManyToManyField(to='Portfolio.tools')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
    ]
