# Generated by Django 5.2.5 on 2025-08-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_tools_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tools',
            options={'verbose_name': 'Tool', 'verbose_name_plural': 'Tools'},
        ),
    ]
