# Generated by Django 5.2.5 on 2025-08-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_alter_tools_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='tools',
            field=models.ManyToManyField(related_name='mytool', to='Portfolio.tools'),
        ),
    ]
